<?php
/** @package Coral::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CategoriaRelatoMap.php");

/**
 * CategoriaRelatoDAO provides object-oriented access to the categoria_relato table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Coral::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CategoriaRelatoDAO extends Phreezable
{
	/** @var int */
	public $IdCategoria;

	/** @var date */
	public $AdiconadoEmCategoria;

	/** @var longblob */
	public $IconeCategoria;

	/** @var int */
	public $OrdemCategoria;

	/** @var string */
	public $NomeCategoria;


	/**
	 * Returns a dataset of Relato objects with matching CategoriaRelatoIdCategoria
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCategoriaRelatoIdCategoriaRelatos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_RELATO_CATEGORIA_RELATO1", $criteria);
	}


}
?>