<?php
/** @package Coral::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("DenunciaRelatoMap.php");

/**
 * DenunciaRelatoDAO provides object-oriented access to the denuncia_relato table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Coral::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class DenunciaRelatoDAO extends Phreezable
{
	/** @var int */
	public $IdDenunciaRelato;

	/** @var date */
	public $DataDenunciaRelato;

	/** @var int */
	public $TotalVisualizacaoDenunciaRelato;

	/** @var int */
	public $TotalConfirmacaoExistenciaRelato;

	/** @var string */
	public $DescricaoDenunciaRelato;

	/** @var string */
	public $TituloDenunciaRelato;

	/** @var int */
	public $RelatoIdRelato;

	/** @var int */
	public $UsuarioCpfUsuario;


	/**
	 * Returns the foreign object based on the value of RelatoIdRelato
	 * @return Relato
	 */
	public function GetRelatoIdRelatoRelato()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_DENUNCIA_RELATO_RELATO1");
	}

	/**
	 * Returns the foreign object based on the value of UsuarioCpfUsuario
	 * @return Usuario
	 */
	public function GetCpfUsuarioUsuario()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_denuncia_relato_usuario1");
	}


}
?>