<?php
/** @package Coral::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("DiretoriaMap.php");

/**
 * DiretoriaDAO provides object-oriented access to the diretoria table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Coral::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class DiretoriaDAO extends Phreezable
{
	/** @var int */
	public $IdDiretoria;

	/** @var string */
	public $NomeDiretoria;

	/** @var string */
	public $DescricaoDiretoria;


	/**
	 * Returns a dataset of Funcionario objects with matching DiretoriaIdDiretoria
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetDiretoriaIdDiretoriaFuncionarios($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_FUNCIONARIO_DIRETORIA1", $criteria);
	}

	/**
	 * Returns a dataset of Servico objects with matching DiretoriaIdDiretoria
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetDiretoriaIdDiretoriaServicos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_SERVICO_DIRETORIA1", $criteria);
	}


}
?>