<?php
/** @package Coral::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("FuncionarioMap.php");

/**
 * FuncionarioDAO provides object-oriented access to the funcionario table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Coral::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class FuncionarioDAO extends Phreezable
{
	/** @var int */
	public $MatriculaFuncionario;

	/** @var int */
	public $DiretoriaIdDiretoria;

	/** @var int */
	public $UsuarioCpfUsuario;


	/**
	 * Returns the foreign object based on the value of DiretoriaIdDiretoria
	 * @return Diretoria
	 */
	public function GetDiretoriaIdDiretoriaDiretoria()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_FUNCIONARIO_DIRETORIA1");
	}

	/**
	 * Returns the foreign object based on the value of UsuarioCpfUsuario
	 * @return Usuario
	 */
	public function GetCpfUsuarioUsuario()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_funcionario_usuario1");
	}


}
?>