<?php
/** @package Coral::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("LogLoginMap.php");

/**
 * LogLoginDAO provides object-oriented access to the log_login table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Coral::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class LogLoginDAO extends Phreezable
{
	/** @var int */
	public $IdLogin;

	/** @var date */
	public $DataInicioLogin;

	/** @var string */
	public $LocalLogin;

	/** @var string */
	public $PlataformaLogin;

	/** @var timestamp */
	public $TimeZoneLogin;

	/** @var date */
	public $DataFimLogin;

	/** @var int */
	public $UsuarioCpfUsuario;

	/** @var string */
	public $BrowserLogin;


	/**
	 * Returns the foreign object based on the value of UsuarioCpfUsuario
	 * @return Usuario
	 */
	public function GetUsuarioCpfUsuarioUsuario()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_LOG_LOGIN_USUARIO1");
	}


}
?>