<?php
/** @package Coral::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("RelatoMap.php");

/**
 * RelatoDAO provides object-oriented access to the relato table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Coral::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class RelatoDAO extends Phreezable
{
	/** @var int */
	public $IdRelato;

	/** @var string */
	public $DescricaoRelato;

	/** @var string */
	public $StatusRelato;

	/** @var int */
	public $LatitudeRelato;

	/** @var int */
	public $LongitudeRelato;

	/** @var string */
	public $TituloRelato;

	/** @var longblob */
	public $ImagemRelato;

	/** @var date */
	public $AdicionadoEmRelato;

	/** @var date */
	public $PublicadoEmRelato;

	/** @var string */
	public $Logradouro_relato;

	/** @var string */
	public $ComplementoRelato;

	/** @var int */
	public $NumeroRelato;

	/** @var string */
	public $EstadoRelato;

	/** @var string */
	public $BairroRelato;

	/** @var string */
	public $CidadeRelato;

	/** @var int */
	public $Cep_relato;

	/** @var int */
	public $CategoriaRelatoIdCategoria;

	/** @var int */
	public $LocalPermitidoIdLocal;


	/**
	 * Returns a dataset of DenunciaRelato objects with matching RelatoIdRelato
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetRelatoIdRelatoDenunciaRelatos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_DENUNCIA_RELATO_RELATO1", $criteria);
	}

	/**
	 * Returns a dataset of UsuarioRelato objects with matching RelatoIdRelato
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetRelatoIdRelatoUsuarioRelatos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_USUARIO_RELATO_RELATO1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of CategoriaRelatoIdCategoria
	 * @return CategoriaRelato
	 */
	public function GetCategoriaRelatoIdCategoriaCategoriaRelato()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_RELATO_CATEGORIA_RELATO1");
	}

	/**
	 * Returns the foreign object based on the value of LocalPermitidoIdLocal
	 * @return LocalPermitido
	 */
	public function GetLocalPermitidoIdLocalLocalPermitido()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_RELATO_LOCAL_PERMITIDO1");
	}


}
?>