<?php
/** @package Coral::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("TipoUsuarioMap.php");

/**
 * TipoUsuarioDAO provides object-oriented access to the tipo_usuario table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Coral::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class TipoUsuarioDAO extends Phreezable
{
	/** @var int */
	public $IdTipoUsuario;

	/** @var string */
	public $TituloTipoUsuario;

	/** @var string */
	public $DescricaoTipoUsuario;


	/**
	 * Returns a dataset of Usuario objects with matching TipoUsuarioIdTipoUsuario
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetTipoUsuarioIdTipoUsuarioUsuarios($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_USUARIO_TIPO_USUARIO", $criteria);
	}


}
?>