<?php
/** @package Coral::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("UsuarioMap.php");

/**
 * UsuarioDAO provides object-oriented access to the usuario table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Coral::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class UsuarioDAO extends Phreezable
{
	/** @var int */
	public $CpfUsuario;

	/** @var string */
	public $EmailUsuario;

	/** @var longblob */
	public $FotoUsuario;

	/** @var string */
	public $SenhaUsuario;

	/** @var string */
	public $NomeUsuario;

	/** @var int */
	public $TipoUsuarioIdTipoUsuario;


	/**
	 * Returns a dataset of DenunciaRelato objects with matching UsuarioCpfUsuario
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCpfUsuarioDenunciaRelatos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_denuncia_relato_usuario1", $criteria);
	}

	/**
	 * Returns a dataset of Funcionario objects with matching UsuarioCpfUsuario
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCpfUsuarioFuncionarios($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_funcionario_usuario1", $criteria);
	}

	/**
	 * Returns a dataset of LogLogin objects with matching UsuarioCpfUsuario
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetUsuarioCpfUsuarioLogLogins($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_LOG_LOGIN_USUARIO1", $criteria);
	}

	/**
	 * Returns a dataset of Relatante objects with matching UsuarioCpfUsuario
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCpfUsuarioRelatantes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_relatante_usuario1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of TipoUsuarioIdTipoUsuario
	 * @return TipoUsuario
	 */
	public function GetTipoUsuarioIdTipoUsuarioTipoUsuario()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_USUARIO_TIPO_USUARIO");
	}


}
?>